@host = http://localhost
@port = 7160
@token = CfDJ8NxFxRDRP-9FvfL4_OavmvTuOTStjxppDdhNMekqP0KfBa6kA0MGXNpDZgAm15Q4m7-DzvCQAl87na-hVnk7EjFu6d-ifelXeGfMQlg5DnQb4gBGkvcxSQamsZEj3LYMS9plxApCCiQ6BmC1wBi13CgKspZVOSbkUK_DG1pSph4UJW2cdeAqhTWY8gTQ00uCnWA3hI9EakKVcGP16YNlWFoJslzbSln4GeS_B1TCWRLhpHPsqS1Ojm5FFzk0ZikzAFRyyw_Ud1PwqGxwpeEcwKsvb6j7zwyZr6M7SnoHnFUUD5YTvM-NQpRJwEMx6d32R-BteJgOmjvtYMc8daNHl7UrbFEewSuQLfRCZiHTGAXYhCAjA2CYlug_Pl5oVP1ugSjVDS10xzCpRQcti7WA6ODVAvXEEg2N9sr1wJse5cUK5iP8T8zslGzPztK69z2OkBOvG_zATAEOV_lF_gd--447FRt5Y6L2_oL5m1BHR2lDeL52vzDuIaHyCN1d3yLF2hntevvH78tn7EiurTDiS7Aza03RMFRXMJ43FJ2f3bmBePmyzPcvR-aQ1vsLJpL6ZC2ngCZhTkJONZ1WVK1-4v6Lly3ZCckqIxmOD1J7OkrwfpwxLSf4K6DeoXasoWWKA0JQ736rDTPgMAESvD61zXAfqIFh1ljCwNV3jEyeNQxrywtbfuY0rd3pO12uRDGmo44S7fQaxKGAAmpUA_goGupuRSzy_JvwejOcPoz75o9Hz2MVpazAasXT6b83LVBLf9Bjgz3cD9_vvgkkvYYVVig
@Restaurants.API_HostAddress = https://localhost:7160

GET {{Restaurants.API_HostAddress}}/api/restaurants



###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name" : "Naanas Restaurants",
  "Description" : "A Authentic Sri Lankan Foods",
  "Category" : "Indian",
  "HasDelivery" : true,
  "ContactEmail" : "info@naanas.com",
  "ContactNumber" : "0372253198",
  "City" : "Galgamuwa",
  "Street" : "Kurunegala Road",
  "PostalCode": "54-321"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
 
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name" : "Sample Patch2",
  "Description" : "This is a sample restaurant Description 2",
  "HasDelivery" : false

}

###



POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "Name" : "Dolphin kottu",
  "Description" : "Sri Lankan Style Kottu",
  "Price" : 10.05,
  "KiloCalories" : 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes/1

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes/5

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{ 
  "dateOfBirth": "2024-11-07",
  "nationality": "Lankan"
}

###
