@host = http://localhost
@port = 7160
@token = CfDJ8NxFxRDRP-9FvfL4_OavmvTH8ZxYDaIOLGhx5pwBemHmvrAzyuTSqKm5hRz6n4wVDI9Wv4EauwK7AAsiCTky-buAUORX5bp_HJQqO8_gqy5SePWJvWNBtYAMo_niYSgO296LRITBGuRliqdTLqZM0IKYPIPCOaOwdM7TAm-LghHfU3Tn8PYKDkkKyjHlxXx2OU8j7dDkSV-W9PeplbS0mJMguv-iiHo6UVu2H2wju0eSyxUgc2SMKBkNIEXIf2gYD6AlZ9VzzH2bapqO9v4y8D05-7gjrE1XPgVu0afBsiQ2kxDg8aW2nv0PwERqgzgefoJUpHPJEIBI4Bh5oJfv1ZAI0ykTEufSb-_WrLacFTVcfO_FS-qHpFJtaVkRjSoNlKn8rjXZPkjjwDx_9TO5QsUAlhWkVE58J8jOwksYgTkyAwcApt33swtYri2MHhkHonqOJrGqzgrUTFZMFqAap-lEu5_FM3OY9eoc9TK13lRdfQFv1owrkwyDBd4NrWFqvyeDxNU-eOnFEMVRTMseYzeFBX4ucNDaAKQUU0sT9gmGfKJNIjDKSLvZuyBqqh6U6kGFNJtfh80LQlEORDVkj_8rK0Gbi_LQZHHQx5Yzxq9NgYvAB241JCUVHjBakXL3e7urpjZO18cFyWyF_2mtGXIG72T_FRENVFXqx3Wnusjf4Dm5AxVeVnJ0d5aIyuyPGcrpad21ScHcYwxKSf69Rwn0_NTpeVb6ljd6W2_Gi9nqbNy4ftjd8huZ9MNdaTLpdpcRonHEHNUtv-7BweuUldY


@Restaurants.API_HostAddress = https://localhost:7160

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}


###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name" : "Naanas Restaurants",
  "Description" : "A Authentic Sri Lankan Foods",
  "Category" : "Indian",
  "HasDelivery" : true,
  "ContactEmail" : "info@naanas.com",
  "ContactNumber" : "0372253198",
  "City" : "Galgamuwa",
  "Street" : "Kurunegala Road",
  "PostalCode": "54-321"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
 
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name" : "Sample Patch2",
  "Description" : "This is a sample restaurant Description 2",
  "HasDelivery" : false

}

###



POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "Name" : "Dolphin kottu",
  "Description" : "Sri Lankan Style Kottu",
  "Price" : 10.05,
  "KiloCalories" : 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes/1

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes/5

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{ 
  "dateOfBirth": "2010-10-10",
  "nationality": "French"
}

###

