@host = http://localhost
@port = 7160
@token = CfDJ8NxFxRDRP-9FvfL4_OavmvQiV1mXZNYmgm2LgQeHIzSFb666v04VFmXzDIY5o-WNH5XkzEu5OBt0o-9XmJjd211nXnO3CL5I_tmrNRjQZQ9WF-SHIMVHif8XVmjgsp09tZC5IqILWrzXTEJxScZZ6o7TtWVdvP9sw0FRCKgNhUEyOucNY6OF_2veAcAx1tAnSnV_MlgGy0kO2H5wPnQemNEuCQqdnLmOrPQO5UpIastCUEkQcXXeuZLl3eylOLD1VRxSjBRwQVa15V6rCv7uSOEc3CeawIS4zOPTyNhOSgGmgbDwhrrKu0mGIPGFdOG1BIE17VdYuzLEHGN9u1q2kqsSvrXD-HHOJMT78ds72szArjF_OoPaneDe3ELTNIJNncnHhw5BMwrMc7fqldtp5A1zrUHniO4SX3uipbaQNx58DAlMY2O_VBAO0XNus1D-8YvLqIxGK9cKzdMa7VfbccPkYnqgemznd79pw_yH8Kiud0Wvpu70lWfig44yw1ncFKKzWsRbeYLwQI3-X9bb8a1Dve1qNRLp8M0q5ix5tkOzwz8nyc1Bo1EKic7Y1EirXqu5nlZoJnX_a6K7PsADu6lKzeojkBdXiXca0xusehykeXFQVeYQqJzDfZuQk72rAbFbx-1TpRBD3mRCNYORZ6yWe4orLdxRmFhvMtDY2WFp9ZH9vAyVtaJgewZ8TZwP2TixDoVHn3moorv4YAjsUxkGU12I0TV98QqDJBX79aqlvQwXrs8qnj4nYs84PZKiA_do7jorLYakfQn8sEPpV06-hgEakZ4dJ8AVmPBlGYNglWD2Nu9gW0h-nXTNanUL5VxUw9YCywVIfo3mJqXp7tBHR53Pyu-why-5aGYXJeyT1p_pLaB--XUxmYwiy922Kw
@Restaurants.API_HostAddress = https://localhost:7160

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}


###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name" : "Naanas Restaurants",
  "Description" : "A Authentic Sri Lankan Foods",
  "Category" : "Indian",
  "HasDelivery" : true,
  "ContactEmail" : "info@naanas.com",
  "ContactNumber" : "0372253198",
  "City" : "Galgamuwa",
  "Street" : "Kurunegala Road",
  "PostalCode": "54-321"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
 
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/7

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/8
Content-Type: application/json

{
  "Name" : "Sample Patch2",
  "Description" : "This is a sample restaurant Description 2",
  "HasDelivery" : false

}

###



POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "Name" : "Dolphin kottu",
  "Description" : "Sri Lankan Style Kottu",
  "Price" : 10.05,
  "KiloCalories" : 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes/1

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes/5

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{ 
  "dateOfBirth": "2020-10-10",
  "nationality": "French"
}

###

